	LIST	P=PIC16F84A
	INCLUDE	"P16F84A.INC"
	
	__CONFIG	_HS_OSC
	
	ORG		0H
MAIN
	BSF		STATUS,	RP0	;Bank 1
	CLRF	TRISB		;PortB->Output
	MOVLW	01FH		;
	MOVWF	TRISA		;
	BCF		STATUS,	RP0	;Bank 0
	CLRF	PORTB		;ALL RB->Low
LOOP
	MOVF	PORTA,	 W  ;
	MOVWF	PORTB		;
	GOTO	LOOP
	END