		LIST	P=PIC16F84A
		INCLUDE	"P16F84A.INC"
		
		__CONFIG	_HS_OSC
		
TMP0	EQU		0CH		
TMP1	EQU		0DH
		ORG		0H

MAIN
		BSF		STATUS, RP0		;初期設定開始
		CLRF	TRISB			;ポートAを入力に
		MOVLW	01FH			;Wレジスタに01FHを
		MOVWF	TRISA			;TRISBにWを
		BCF		STATUS,	RP0		;初期設定終了
		CLRF	PORTB			;ポートBをクリア
LOOP
		MOVF	PORTA,	W
		ANDLW	B'00000001'
		MOVWF	TMP0
		MOVF	PORTA,	W
		ANDLW	B'00000010'
		MOVWF	TMP1
		BCF		STATUS,	C
		RRF		TMP1,	W
		IORWF	TMP0,	W
		MOVWF	PORTB
		GOTO	LOOP
		END
		