			LIST P=PIC16F84A
			#INCLUDE<P16F84A.INC>

			__CONFIG	_HS_OSC&_CP_OFF&_WDT_OFF&_PWRTE_ON

W_TEMP		EQU		0CH
STATUS_TEMP	EQU		0DH
CNT1		EQU		0EH
CNTB		EQU		0FH
IN			EQU		012H

			ORG		0H
			GOTO	MAIN

			ORG		04H

;PUSH
			MOVWF	W_TEMP
			MOVF	STATUS,W
			MOVWF	STATUS_TEMP

			MOVLW	'O'
			CALL	CSEND
			MOVLW	'K'
			CALL	CSEND
			MOVLW	'A'
			CALL	CSEND
			MOVLW	'W'
			CALL	CSEND
			MOVLW	'A'
			CALL	CSEND
			MOVLW	' '
			CALL	CSEND
			MOVLW	'M'
			CALL	CSEND
			MOVLW	'A'
			CALL	CSEND
			MOVLW	'S'
			CALL	CSEND
			MOVLW	'A'
			CALL	CSEND
			MOVLW	'R'
			CALL	CSEND
			MOVLW	'U'
			CALL	CSEND
			MOVLW	B'00001101'
			CALL	CSEND
			MOVLW	B'00001010'
			CALL	CSEND

;POP
			MOVF	STATUS_TEMP,W
			MOVWF	STATUS
			SWAPF	W_TEMP,F
			SWAPF	W_TEMP,W
			BCF		INTCON,INTF	;CLEAR INTERRUPT FLAG

;REMAING CODE GOES HERE

MAIN
			BSF		STATUS,RP0	;BANK1
			BCF		INTCON,GIE	;DISABLE INTERRUPTS
			CLRF	TRISA		;RA->OUTPUT
			MOVLW	01H
			MOVWF	TRISB		;RB0->INPUT
			BCF		STATUS,RP0	;BANK0
			BSF		PORTA,4		;RS232C->HIGH
			BSF		INTCON,GIE	;ENABLE INTERRUPTS
			BSF		INTCON,INTE

MAINLP
			GOTO	MAINLP

CSEND
			MOVWF	IN			;WREG->CHARACTOR CODE
			MOVLW	08H
			MOVWF	CNTB
			BCF		PORTA,4		;START BIT
			CALL	TIME104		;DELAY 104U
CSENDLP
			BTFSC	IN,0
			BSF		PORTA,4
			BTFSS	IN,0
			BCF		PORTA,4
			CALL	TIME104
			RRF		IN,F
			DECFSZ	CNTB,F
			GOTO	CSENDLP
			BSF		PORTA,4
			CALL	TIME104
			RETURN

;104US
TIME104
			MOVLW	082H
			MOVWF	CNT1
LOOP2
			NOP
			DECFSZ	CNT1,F
			GOTO	LOOP2
			RETURN

			END